# Generated by Django 4.0.4 on 2022-05-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_achivement_new_person_project_delete_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='imagem',
            field=models.ImageField(upload_to='static/portfolio/images'),
        ),
    ]
