# Generated by Django 4.0.4 on 2022-05-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_new_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
