# Generated by Django 4.0.4 on 2022-05-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_rename_data_project_ano_alter_project_cadeira_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('descricao', models.TextField(max_length=2000)),
                ('ects', models.IntegerField()),
                ('data', models.DateField()),
                ('topicosabordados', models.CharField(max_length=1000)),
                ('ranking', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='link',
        ),
        migrations.AddField(
            model_name='project',
            name='linkgithub',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='new',
            name='link',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='new',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='ano',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='participantes',
            field=models.CharField(max_length=100),
        ),
    ]
