# Generated by Django 4.0.4 on 2022-05-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_chair_remove_project_link_project_linkgithub_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=1000)),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('texto', models.TextField(max_length=1000)),
                ('imagem', models.ImageField(upload_to='static/portfolio/images')),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('acronimo', models.CharField(max_length=10)),
                ('ano', models.IntegerField()),
                ('criador', models.CharField(max_length=20)),
                ('logotipo', models.ImageField(upload_to='static/portfolio/images')),
                ('link', models.CharField(max_length=500)),
                ('descricao', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='chair',
            name='descricao',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='chair',
            name='ranking',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chair',
            name='topicosabordados',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='new',
            name='descricao',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='ano',
            field=models.DateField(max_length=4),
        ),
    ]
