# Generated by Django 4.0.4 on 2022-05-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_lab_noticia_tecnologia_alter_chair_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='autor',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='project',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='criador',
            field=models.CharField(max_length=40),
        ),
    ]
