# Generated by Django 4.0.4 on 2022-05-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_remove_chair_topicosabordados_remove_person_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chair',
            name='data',
        ),
        migrations.AlterField(
            model_name='person',
            name='nome',
            field=models.CharField(max_length=60),
        ),
    ]
