# Generated by Django 4.0.4 on 2022-05-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_remove_chair_data_alter_person_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnologia',
            name='acronimo',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
