# Generated by Django 4.0.4 on 2022-05-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_tecnologia_acronimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ano',
            field=models.IntegerField(),
        ),
    ]
