# Generated by Django 4.0.4 on 2022-05-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_project_tecnologia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='titulo',
            field=models.CharField(max_length=70),
        ),
    ]
