# Generated by Django 4.0.4 on 2022-05-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_lab_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formacao', models.CharField(max_length=70)),
                ('curso', models.CharField(max_length=40)),
                ('local', models.CharField(max_length=50)),
                ('periodo', models.CharField(max_length=50)),
                ('logotipo', models.ImageField(upload_to='static/portfolio/images')),
            ],
        ),
    ]
