# Generated by Django 4.0.4 on 2022-05-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='curso',
            field=models.CharField(max_length=60),
        ),
    ]
