# Generated by Django 4.0.4 on 2022-05-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_alter_education_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='TFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('sumario', models.TextField(max_length=1000)),
                ('linkGitHub', models.CharField(max_length=1000)),
                ('linkYoutube', models.CharField(max_length=1000)),
                ('linkRelatorio', models.CharField(max_length=1000)),
                ('ano', models.IntegerField()),
                ('autor', models.CharField(max_length=70)),
                ('orientador', models.CharField(max_length=70)),
            ],
        ),
        migrations.RemoveField(
            model_name='achivement',
            name='competencias',
        ),
        migrations.AddField(
            model_name='achivement',
            name='cadeira',
            field=models.CharField(default='1', max_length=40),
        ),
        migrations.AddField(
            model_name='achivement',
            name='descricao',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='achivement',
            name='projetos',
            field=models.ManyToManyField(blank=True, to='portfolio.project'),
        ),
        migrations.AddField(
            model_name='achivement',
            name='titulo',
            field=models.CharField(default='1', max_length=70),
        ),
    ]
