# Generated by Django 4.0.4 on 2022-05-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='pergunta_0',
            field=models.IntegerField(default=0),
        ),
    ]
