# Generated by Django 4.0.4 on 2022-05-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_quiz_pergunta_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontuacaoQuizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('apelido', models.CharField(max_length=20)),
                ('pontuacao', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.AlterField(
            model_name='new',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='static/portfolio/images'),
        ),
    ]
