# Generated by Django 4.0.4 on 2022-05-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_pontuacaoquizz_delete_quiz_alter_new_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='imagem',
            field=models.ImageField(default='1', upload_to='static/portfolio/images'),
        ),
    ]
