# Generated by Django 4.0.4 on 2022-05-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_education_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='topicos',
            field=models.CharField(default='1', max_length=500),
        ),
    ]
